### PR TITLE
Increase range on TimeThing test

### PR DESCRIPTION
**Pull request by bobbyangers**
Increased range for **TestTimeThings.TestTimeThingResultReturn**
Also implemented **MockOutput**

### CODE REVIEW

**Comment by bobbyangers** [comment]
Hi @JonPSmith,

When are you planning to release this version ?  Are you expecting to upgrade the version to 5.0.1 to match EntityFrameworkCore ?

**Comment by JonPSmith** [comment]
Hi @bobbyangers,

As you can see I'm currently working on the EF Core 5 version, which has a LOT of changes. It also needs the new `EfCore.SchemaCompare` library, as I have removed this from this version. Should be out in a week or so.

PS. Why did you change  the time in the `TestTimeThings` code? Didn't it work?

**Comment by bobbyangers** [comment]
> PS. Why did you change the time in the `TestTimeThings` code? Didn't it work?

On my computer, it consistently be more than 20....  25, 35;

**Comment by bobbyangers** [comment]
@JonPSmith -> 5.0.1 solves quite a few issues.

Here is some help.  Looking forward to using the new version of the library.

**Comment by JonPSmith** [comment]
Hi @bobbyangers,

It's always polite to ask before adding pull requests. In this case I'm not going to merge your changes but I will update the time in the unit test.

**Comment by bobbyangers** [comment]
> It's always polite to ask before adding pull requests. In this case I'm not going to merge your changes but I will update the time in the unit test.

Ok I am sorry, about that; 
I do believe that is the whole point of a PR is to submit changes and  permit the maintainer to review....  and accept or not; which is implicitly asking, no ? (since you have the veto) 

So what would be the proper way of asking ?

Again, sorry if you are offended.   Was just trying to contribute.

**Comment by JonPSmith** [comment]
Thanks. I have added something to the README file about pull requests. I have a lot of libraries to support and random pull requests are hard to fit in, especially if it requires a new NuGet or document change. In your case I have updated the timeout you changed. 

PS. There is a preview of this library [on NuGet](https://www.nuget.org/packages/EfCore.TestSupport/5.0.0-preview006) if you want to try it. Remember your version of EF Core will override the one in the library,

**Pull request closed without merging**
