### PR TITLE
Dotnet 7 support

### PR DESCRIPTION
**Pull request by chrisbbe**

### CODE REVIEW

**Comment by JonPSmith** [comment]
Hi @chrisbbe,

Thanks for this PR - helps me a lot as I have about 10 libraries to update. I will look at this soon.

Can you tell me a bit more on the Npgsql 7.0 change?

**Comment by chrisbbe** [comment]
Your welcome,

Npgsql 7.0 has made the `Settings` property on `NpgsqlConnection` internal or private, which was used to retrieve the enum property `ServerCompatibilityMode` in the `DropCollations()` method.

To retrieve the `ServerCompatibilityMode` property in Npgsql7.0 i simply initiate a new instance of `NpgsqlConnectionStringBuilder` with the connection-string being used and have public access to the enum property from there.

**Comment by chrisbbe** [comment]
Superb, can you release a new version to NuGet please?

**Comment by JonPSmith** [comment]
The .NET 7 part of the library has seven errors, so I need to sort these out before I can release the NuGet.

**Comment by JonPSmith** [comment]
Hi @chrisbbe,

~~Could you send me a link to the information about the Settings property on NpgsqlConnection. Your change has broken all the versions (.NET 7, NET 7, and netcoreapp3.1) of the `NpgsqlDatabaseCleaner` and I can't get it back.~~

Until this is fixed I can't release this.

**Comment by JonPSmith** [comment]
Hi @chrisbbe,

Not so sure that the NpgsqlConnection setting is the problem - also got a problem with SQL Server. Ignore my last request for now.

**Comment by JonPSmith** [comment]
Hi @chrisbbe,

I have released [version 5.3.0](https://www.nuget.org/packages/EfCore.TestSupport/5.3.0). It wasn't a simple update with changes to logging, but the main problem with the VS2022's xUnit runner which runs all the target frameworks at the same time, which wasn't obvious (Resharper's xUnit runner doesn't do that). This caused problems.

So, your PR code was fine, but I was confused by VS2022's xUnit runner, which also showed up a error in the `EnsureClean` tests if the test database had entities in it.

Thanks for your help.

**Pull request merged**
